name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Wird ausgelöst, wenn Änderungen in den main-Branch gepusht werden

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Hier kannst du Build-Schritte einfügen, wenn du sie benötigst
      # Zum Beispiel für eine JavaScript/Node.js-Anwendung:
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build site
      #   run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Der Branch, in den deployed werden soll
          folder: .         # Der Ordner, der deployed werden soll (anpassen je nach Projekt)
          # folder: dist    # Beispiel für eine Anwendung mit Build-Prozess
          clean: true       # Löscht bestehende Dateien im Ziel-Branch